FROM node:22-alpine

RUN apk add --no-cache \
    bash \
    curl \
    postgresql-client \
    openssl \
    openssl-dev

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]
